FROM openjdk:8-jdk-alpine
EXPOSE 8080
ARG JAR_FILE=target/*.jar
RUN mkdir /data
COPY /data /data
VOLUME /data
COPY ${JAR_FILE} app.jar
ARG REGION_ARG=sa-east-1
ARG ACCESS_ARG
ARG SECRET_ARG
ARG ENVIROMENT
ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$ACCESS_ARG
ENV AWS_SECRET_KEY=$SECRET_ARG
ENV SPRING_PROFILE=$ENVIROMENT
ENTRYPOINT ["java","-Dspring.profiles.active=${SPRING_PROFILE}","-jar","app.jar"]